book:
  title: "2024 Alaska Electricity Trends Report"
  author: "Alaska Center for Energy and Power"
  description: An interactive report that summarizes federal, state, and utility electricity data for Alaska.
  keyword: Alaska, energy, capacity, generation, price, rates

  chapters:
    - index.qmd
    - methods.qmd
    - capacity.qmd
    - generation.qmd
    - consumption.qmd
    - prices.qmd
    - conclusions.qmd
    - data.qmd
  appendices:
    - about.qmd
    - historic_reports.qmd
    - acronyms.qmd
    - credits.qmd 

# These change page titles https://quarto.org/docs/books/book-structure.html#parts-appendices 
# but not in the sidebar navigation or in cross-references
crossref:
  appendix-title: "Appendix"
  appendix-delim: ":"


format:
  pdf:
    pdfengine: xelatex
    documentclass: scrreprt
    papersize: a4

    fontsize: 11pt
    # mainfont: "Times New Roman"
    # sansfont: "Arial"
    # monofont: "Courier New"

    geometry:
      - inner=2cm
      - outer=2cm
      - top=2cm
      - bottom=2cm
      # - headsep=22pt
      # - headheight=11pt
      # - footskip=33pt
      # - ignorehead
      # - ignorefoot
      # - heightrounded

    toc: true   # table of contents
    toc-depth: 3
    toc-title: "Table of contents"
    lof: true   # list of figures
    lot: true   # list of tables
    number-sections: true
    number-depth: 2

    template-partials:
      - scripts/latex/before-body.tex
    include-in-header: 
      - scripts/latex/preamble.tex

date: last-modified
date-format: "MMM D, YYYY [at] HH:mm z"


filters:
  - quarto
  